import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/(Components)/Header';
import Footer from '@/app/(Components)/Footer';

import localFont from 'next/font/local'

// Font files can be colocated inside of `pages`
const SpandanFont = localFont({ src: '../font/FertigoPro-Regular2.otf' })


// const inter = Inter({ subsets: ['latin'] })

const roboto = localFont({
  src: [
    {
      path: '../font/FertigoPro-Regular2.otf',
      weight: '100',
      style: 'normal',
    }
  ],
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={SpandanFont.className}>


        <Header />

        {children}

        <Footer />
        
        </body>
    </html>
  )
}
